drop_list = [
    "*.example.com",
]

redirect_list = [
    "google.com:1.1.1.1,2.2.2.2",
    "*.test.com:192.168.1.1",
    "*.youtube.com:142.251.37.110",
    "*.googlevideo.com:142.250.191.174",
    "*.ytimg.com:142.250.190.14",
    "*.ggpht.com:142.250.72.67"
]

resolvers = [
    # "https://cloudflare-dns.com/dns-query",
    "8.8.8.8:53",
    "1.1.1.1:53",
]

[resolver_searching]
enable = false
resolver_source = [
 "https://public-dns.info/nameservers-all.txt",
 "https://raw.githubusercontent.com/trickest/resolvers/main/resolvers.txt"
]
refresh_interval = 30
ipv4 = true 
doh = true


[hotreload_conf]
enable = true 
poll_interval_ms = 100
