drop_list = [
    "google.com",
    "*.example.com",
]

redirect_list = [
    "*.test.com:192.168.1.1",
]

resolvers = [
    "https://cloudflare-dns.com/dns-query",
    "8.8.8.8:53",
    "1.1.1.1:53",
]
