[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", default-features = false, features = [
    "derive",
    "std",
] }
tokio = { version = "1.52.3", default-features = false, features = ["net"] }
socket2 = "0.5"

aes-gcm = "0.10"
base64 = "0.21"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json",
] }
rand = "0.10.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", default-features = false, features = [
    "fmt",
    "std",
] }
lru = "0.12"
[dev-dependencies]
tempfile = "3"
tokio = { version = "1", features = ["full", "test-util"] }
